name: test1
start_date: 2020-01-31
end_date: 2020-05-31
nsimulations: 1
dt: 0.25

spatial_setup:
  census_year: 2010
  base_path: test1/data
  modeled_states: # To model a region that is not a state, remove modeled_states and the importation: block
   - HI # e.g., MD  You can provide as many of these as you like, but more counties means slower runs
  setup_name: test1
  geodata: geodata.csv
  mobility: mobility.txt
  popnodes: population
  nodenames: geoid
  include_in_report: targeted
  # shapefile: <shapefile.shp> # We haven't created fake shapefiles yet.  Stay tuned.
  # shapefile_name:  <shapefile.shp> # This should be the same as above.  We are working to merge the two

seeding:
  method: PoissonDistributed
  lambda_file: test1/data/seeding.csv

seir:
  parameters:
    sigma: 1 / 5.2
    gamma:
      distribution: uniform
      low: 1 / 6
      high: 1 / 2.6
    R0s:
      distribution: uniform
      low: 2
      high: 3

interventions:
  scenarios:
    - None
    - Scenario1
  settings:
    None:
      template: ReduceR0
      period_start_date: 2020-04-01
      period_end_date: 2020-05-15
      value:
        distribution: fixed
        value: 0
    Place1:
      template: ReduceR0
      period_start_date: 2020-04-01
      period_end_date: 2020-05-15
      value:
        distribution: uniform
        low: .14
        high: .33
    Scenario1:
      template: Stacked
      scenarios:
        - Place1
        - None
hospitalization:
  paths:
    output_path: hospitalization
  parameters:
    time_hosp: [1.23, 0.79]
    time_disch: [log(11.5), log(1.22)]
    time_death: [log(11.25), log(1.15)]
    time_ICU: [log(8.25), log(2.2)]
    time_ICUdur: [log(16), log(2.96)]
    time_vent: [log(10.5), log((10.5-8)/1.35)]
    p_death: [.0025, .005, .01]
    p_death_names: ["low","med","high"]
    p_death_rate: 0.1
    p_ICU: 0.32
    p_vent: 0.15

## Report generation is still in it's infancy.
## The parameters in this block are only used in our draft state_report rmarkdown template 
## This section can be removed if you are not using that template.
## Many of the parameters in this section may be broken, as that report has been under a lot of development recently.
# report:
#   data_settings:
#     pop_year: 2010
#   plot_settings:
#     plot_intervention: TRUE
#     parameters_to_display:
#       sigma:
#         type: seir
#         distribution: exp
#         formal_name: Incubation Period
#         transform: invert
#         xlab: Days since symptom onset
#       gamma:
#         type: seir
#         distribution: gamma
#         formal_name: Duration of Infectiousness
#         transform: invert
#         xlab: Days since symptom onset
#       time_hosp:
#         type: hospitalization
#         distribution: lnormal
#         formal_name: Time to Hospitalization
#         xlab: Days since symptom onset
#         xlim: [0,100]
#       time_disch:
#         type: hospitalization
#         distribution: lnormal
#         formal_name: Time to Discharge
#         xlab: Days since hospitalization
#       time_ICU:
#         type: hospitalization
#         distribution: lnormal
#         formal_name: Time to ICU Admission
#         xlab: Days since hospitalization
#         xlim: [0,100]
#       time_ICUdur:
#         type: hospitalization
#         distribution: lnormal
#         formal_name: Time in ICU
#         xlab: Days since ICU admission
#         xlim: [0,100]
#       time_death:
#         type: hospitalization
#         distribution: lnormal
#         formal_name: Time to Death
#         xlab: Days since hopitalization
#       time_vent:
#         type: hospitalization
#         distribution: lnormal
#         formal_name: Time to Ventilation
#         xlab: Days since ICU admission
#         xlim: [0,100]
#   formatting:
#     scenario_labels_short: []
#     scenario_labels:
#     - Lockdown followed by Worst Case Uncontrolled Spread
#     - Lockdown followed by Test and Isolate
#     - Lockdown followed by Moderate Social Distancing
#     scenario_colors: ["#D95F02", "#1B9E77", "#7570B3"]
#     pdeath_labels: ["0.25% IFR", "0.5% IFR", "1% IFR"]
#     display_dates: ["2020-05-01", "2020-07-01", "2020-09-01"]
